version: '3.9'

services:
  postgres:
    image: postgres
    restart: always

    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=test
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - '5050:80'
